// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrvIr-YljhNeK4e1DK3jfid0bgBQ9hLho',
    appId: '1:681680089277:web:3c289c9f6fdf6bc8f147d4',
    messagingSenderId: '681680089277',
    projectId: 'fruit-hub-da195',
    authDomain: 'fruit-hub-da195.firebaseapp.com',
    storageBucket: 'fruit-hub-da195.firebasestorage.app',
    measurementId: 'G-E8LQCF08SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdko6q-MpPmsHshC2lGfM9XNziJsdTZAU',
    appId: '1:681680089277:android:14ebcca8c5b766c5f147d4',
    messagingSenderId: '681680089277',
    projectId: 'fruit-hub-da195',
    storageBucket: 'fruit-hub-da195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGA0lKhoQpF7BdIqWx1kBE6PNgVfctyqw',
    appId: '1:681680089277:ios:153917ff077148dff147d4',
    messagingSenderId: '681680089277',
    projectId: 'fruit-hub-da195',
    storageBucket: 'fruit-hub-da195.firebasestorage.app',
    androidClientId: '681680089277-0pdmuole3oinulhtt13lbclp5u7fepdt.apps.googleusercontent.com',
    iosClientId: '681680089277-riecl6q8040i6r34qgj63c7elfaskm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGA0lKhoQpF7BdIqWx1kBE6PNgVfctyqw',
    appId: '1:681680089277:ios:153917ff077148dff147d4',
    messagingSenderId: '681680089277',
    projectId: 'fruit-hub-da195',
    storageBucket: 'fruit-hub-da195.firebasestorage.app',
    androidClientId: '681680089277-0pdmuole3oinulhtt13lbclp5u7fepdt.apps.googleusercontent.com',
    iosClientId: '681680089277-riecl6q8040i6r34qgj63c7elfaskm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrvIr-YljhNeK4e1DK3jfid0bgBQ9hLho',
    appId: '1:681680089277:web:31796cd6ef5dc8bef147d4',
    messagingSenderId: '681680089277',
    projectId: 'fruit-hub-da195',
    authDomain: 'fruit-hub-da195.firebaseapp.com',
    storageBucket: 'fruit-hub-da195.firebasestorage.app',
    measurementId: 'G-SQP3024XQM',
  );

}