// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdAWfgNy1v_8PVXQ6Vmieh8ywkAzk1q4',
    appId: '1:485151669727:web:9736d7fcc325a8b94c986a',
    messagingSenderId: '485151669727',
    projectId: 'a3tof-chat',
    authDomain: 'a3tof-chat.firebaseapp.com',
    storageBucket: 'a3tof-chat.firebasestorage.app',
    measurementId: 'G-Q0QY7NV47X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDf3eREJr0xHAfGklT5JNVHWe7UwRQKl4',
    appId: '1:485151669727:android:da12950d825806854c986a',
    messagingSenderId: '485151669727',
    projectId: 'a3tof-chat',
    storageBucket: 'a3tof-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wjgb1zfG9KEa__zlMTvVJphWO2kEiUA',
    appId: '1:485151669727:ios:cb55192d096cf9814c986a',
    messagingSenderId: '485151669727',
    projectId: 'a3tof-chat',
    storageBucket: 'a3tof-chat.firebasestorage.app',
    iosBundleId: 'com.example.fruiteHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wjgb1zfG9KEa__zlMTvVJphWO2kEiUA',
    appId: '1:485151669727:ios:cb55192d096cf9814c986a',
    messagingSenderId: '485151669727',
    projectId: 'a3tof-chat',
    storageBucket: 'a3tof-chat.firebasestorage.app',
    iosBundleId: 'com.example.fruiteHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyP1cVd2Gy114kn6GvTWjdJRrwfnLyZT0',
    appId: '1:485151669727:web:c36057a242e083d74c986a',
    messagingSenderId: '485151669727',
    projectId: 'a3tof-chat',
    authDomain: 'a3tof-chat.firebaseapp.com',
    storageBucket: 'a3tof-chat.firebasestorage.app',
    measurementId: 'G-26KQ916SL3',
  );

}